name: "CD (Entrega/Delivery Continua): Main Workflow"
  
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ci-cd  # Environment name

    steps:
      - uses: actions/checkout@v3

      - name: Check VERCEL_TOKEN
        run: echo token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Runs yarn command
      - name: Run yarn
        run: yarn install

      - name: Run Deploy
        run: yarn deploy:prod